import { Category, Channel, Section } from './types';

export const SECTIONS: Section[] = [
  { id: Category.NEWS, title: 'القنوات الإخبارية' },
  { id: Category.INTERNATIONAL, title: 'قنوات عالمية' },
  { id: Category.ISLAMIC, title: 'القنوات الإسلامية والتعليمية' },
  { id: Category.KIDS, title: 'قنوات الأطفال' },
];

export const CHANNELS: Channel[] = [
  // News
  {
    id: 'almashhad',
    name: 'قناة المشهد',
    description: 'قناة إخبارية عربية مستقلة تقدم الأخبار والتحليلات السياسية.',
    imageUrl: 'https://picsum.photos/seed/almashhad/350/180',
    streamUrl: 'https://www.elahmad.com/tv/almashhad-live.php',
    category: Category.NEWS,
    genre: ['news', 'politics', 'analysis'],
  },
  {
    id: 'aljazeera',
    name: 'قناة الجزيرة',
    description: 'قناة إخبارية عربية مستقلة تقدم الأخبار والتحليلات على مدار الساعة.',
    imageUrl: 'https://picsum.photos/seed/aljazeera/350/180',
    streamUrl: 'https://www.elahmad.com/tv/aljazeera.htm',
    category: Category.NEWS,
    genre: ['news', 'politics', 'documentary'],
  },
  {
    id: 'aljazeera_mubasher',
    name: 'الجزيرة مباشر',
    description: 'البث المباشر للأحداث والتطورات كما تحدث.',
    imageUrl: 'https://picsum.photos/seed/aljazeeramubasher/350/180',
    streamUrl: 'https://www.elahmad.com/tv/aljazeera_mubasher.htm',
    category: Category.NEWS,
    genre: ['news', 'live events', 'current affairs'],
  },
  {
    id: 'alarabiya',
    name: 'قناة العربية',
    description: 'قناة إخبارية عربية تقدم الأخبار والبرامج الحوارية والتقارير الخاصة.',
    imageUrl: 'https://picsum.photos/seed/alarabiya/350/180',
    streamUrl: 'https://www.elahmad.com/tv/alarabiya-tv-live.php',
    category: Category.NEWS,
    genre: ['news', 'talk shows', 'reports'],
  },
  {
    id: 'alhadath',
    name: 'العربية الحدث',
    description: 'قناة متخصصة في متابعة الأحداث الساخنة والتطورات العاجلة.',
    imageUrl: 'https://picsum.photos/seed/alhadath/350/180',
    streamUrl: 'https://www.elahmad.com/tv/alarabiya_alhadath.php',
    category: Category.NEWS,
    genre: ['news', 'breaking news', 'current affairs'],
  },
  {
    id: 'skynewsarabia',
    name: 'سكاي نيوز عربية',
    description: 'قناة إخبارية عربية تابعة لشبكة سكاي نيوز العالمية.',
    imageUrl: 'https://picsum.photos/seed/skynews/350/180',
    streamUrl: 'https://www.elahmad.com/tv/skynewsarabia.php',
    category: Category.NEWS,
    genre: ['news', 'international', 'technology'],
  },
   {
    id: 'alaraby',
    name: 'قناة العربي',
    description: 'قناة إخبارية عربية تقدم الأخبار والبرامج الثقافية.',
    imageUrl: 'https://picsum.photos/seed/alaraby/350/180',
    streamUrl: 'https://www.elahmad.com/tv/alaraby-tv.php',
    category: Category.NEWS,
    genre: ['news', 'culture', 'variety'],
  },


  // International
  {
    id: 'bbcarabic',
    name: 'بي بي سي عربي',
    description: 'الخدمة الإخبارية باللغة العربية من هيئة الإذاعة البريطانية.',
    imageUrl: 'https://picsum.photos/seed/bbc/350/180',
    streamUrl: 'https://www.elahmad.com/tv/bbc_ar.php',
    category: Category.INTERNATIONAL,
    genre: ['news', 'international', 'documentary'],
  },
  {
    id: 'france24',
    name: 'فرانس 24 عربي',
    description: 'تقدم الأخبار الدولية من وجهة نظر فرنسية.',
    imageUrl: 'https://picsum.photos/seed/france24/350/180',
    streamUrl: 'https://www.elahmad.com/tv/france24_ar.php',
    category: Category.INTERNATIONAL,
    genre: ['news', 'international', 'european perspective'],
  },
  {
    id: 'dw',
    name: 'دويتشه فله',
    description: 'قناة دويتشه فيله الألمانية الناطقة باللغة العربية.',
    imageUrl: 'https://picsum.photos/seed/dw/350/180',
    streamUrl: 'https://www.elahmad.com/tv/deutsche_welle.php',
    category: Category.INTERNATIONAL,
    genre: ['news', 'international', 'german perspective'],
  },
  {
    id: 'rtarabic',
    name: 'RT Arabic',
    description: 'الخدمة الإخبارية باللغة العربية من روسيا.',
    imageUrl: 'https://picsum.photos/seed/rt/350/180',
    streamUrl: 'https://www.elahmad.com/tv/rtarabicru.php',
    category: Category.INTERNATIONAL,
    genre: ['news', 'international', 'russian perspective'],
  },

  // Islamic
  {
    id: 'quran',
    name: 'قناة القرآن الكريم',
    description: 'قناة متخصصة في بث القرآن الكريم تلاوة وتفسيراً.',
    imageUrl: 'https://picsum.photos/seed/quran/350/180',
    streamUrl: 'https://www.elahmad.com/tv/qurantv.php',
    category: Category.ISLAMIC,
    genre: ['islamic', 'religious', 'quran'],
  },
  {
    id: 'sunnah',
    name: 'قناة السنة',
    description: 'قناة إسلامية متخصصة في بث الأحاديث النبوية وعلومها.',
    imageUrl: 'https://picsum.photos/seed/sunnah/350/180',
    streamUrl: 'https://www.elahmad.com/tv/sunnatv.php',
    category: Category.ISLAMIC,
    genre: ['islamic', 'religious', 'sunnah'],
  },
  {
    id: 'iqraa',
    name: 'قناة إقرأ',
    description: 'قناة إسلامية تعليمية تقدم برامج دينية وثقافية.',
    imageUrl: 'https://picsum.photos/seed/iqraa/350/180',
    streamUrl: 'https://www.elahmad.com/tv/iqraa-tv.php',
    category: Category.ISLAMIC,
    genre: ['islamic', 'educational', 'cultural'],
  },
  {
    id: 'majd',
    name: 'قناة المجد',
    description: 'قناة إسلامية سعودية تقدم البرامج الدينية والثقافية.',
    imageUrl: 'https://picsum.photos/seed/majd/350/180',
    streamUrl: 'https://www.elahmad.com/tv/almajdtv.php',
    category: Category.ISLAMIC,
    genre: ['islamic', 'family', 'conservative'],
  },
  
  // Kids
  {
    id: 'baraem',
    name: 'قناة براعم',
    description: 'قناة أطفال عربية تقدم برامج تعليمية وترفيهية للأطفال الصغار.',
    imageUrl: 'https://picsum.photos/seed/baraem/350/180',
    streamUrl: 'https://www.elahmad.com/tv/mobiletv/glarb.php?id=baraem',
    category: Category.KIDS,
    genre: ['kids', 'educational', 'preschool'],
  },
  {
    id: 'majidkids',
    name: 'قناة ماجد',
    description: 'قناة أطفال تقدم برامج كرتونية وتعليمية هادفة.',
    imageUrl: 'https://picsum.photos/seed/majidkids/350/180',
    streamUrl: 'https://www.elahmad.com/tv/live/adtv_live.php?id=majid',
    category: Category.KIDS,
    genre: ['kids', 'animation', 'educational'],
  },
  {
    id: 'spacetoon',
    name: 'قناة سبيس تون',
    description: 'قناة أطفال تقدم أشهر برامج الكرتون والرسوم المتحركة.',
    imageUrl: 'https://picsum.photos/seed/spacetoon/350/180',
    streamUrl: 'https://www.elahmad.com/tv/mobiletv/glarb.php?id=spacetoon',
    category: Category.KIDS,
    genre: ['kids', 'animation', 'cartoon'],
  },
  {
    id: 'karameesh',
    name: 'قناة كراميش',
    description: 'قناة أطفال تقدم برامج ترفيهية وتعليمية ممتعة.',
    imageUrl: 'https://picsum.photos/seed/karameesh/350/180',
    streamUrl: 'https://www.elahmad.com/tv/karameeshtv.php',
    category: Category.KIDS,
    genre: ['kids', 'entertainment', 'songs'],
  },
];